image: ros:eloquent

build:
 stage: build
 script:
   - apt update
   - apt --yes --force-yes install ros-eloquent-interactive-markers
 
   - source /opt/ros/eloquent/setup.bash

   - mkdir -p ros_ws/src

   - rm -f ros_ws/src/rosslt || true
   - ln -s $(pwd) ros_ws/src/rosslt
   
   - cd ros_ws
   - rm -rf build install log

   - colcon build --packages-up-to rosslt_demo
   - source install/local_setup.bash
   
 stage: test
 script:
   - colcon test --packages-up-to rosslt_demo --return-code-on-test-failure
   - colcon test-result
 
 artifacts:
    paths:
        - ros_ws/install
