image: ros:eloquent

create_workspace:
 stage: .pre
 script:
   - apt update -y
   - apt -y install ros-eloquent-interactive-markers
 
   - source /opt/ros/eloquent/setup.bash
   
   - mkdir -p ros_ws/src

   - rm -f ros_ws/src/rosslt || true
   - ln -s $(pwd) ros_ws/src/rosslt
   
   - cd ros_ws
   - rm -rf build install log

build:
 stage: build
 script:
   - colcon build --packages-up-to rosslt_demo
   - source install/local_setup.bash
 artifacts:
    paths:
        - install
